# Numpy Basics

In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.5'

In [3]:
lst = [1, 2, 3, 4, 5]
print(lst, type(lst))

[1, 2, 3, 4, 5] <class 'list'>


In [4]:
print('0D array')
A = np.array(59)
print(A, type(A), A.shape, A.size)

print('1D array')
a = np.array(lst) # numpy array accepts only homogenous elements.
print(a)

#--------------------------
print('2D array')
b = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(b)

#--------------------------
print('3D array')
c = np.array([[lst,[i for i in range(6,11)], [11, 12, 13, 14, 15]]])
print(c)

0D array
59 <class 'numpy.ndarray'> () 1
1D array
[1 2 3 4 5]
2D array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3D array
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [5]:
# to check the dimension of the array
print(A.ndim,a.ndim,b.ndim,c.ndim)

0 1 2 3


In [6]:
print(np.array([4,5,6,6,7], ndmin=1)) # to declare: "ndmin", to get dimensionality: ndim
print(np.array([4,5,6,6,7], ndmin=2))
print(np.array([4,5,6,6,7], ndmin=3))

[4 5 6 6 7]
[[4 5 6 6 7]]
[[[4 5 6 6 7]]]


In [7]:
print(type(a))
print(type(b))
print(type(c))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [8]:
print(a.size)
print(b.size)
print(c.size)

5
10
15


In [9]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(1, 3, 5)


In [10]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
int32
int32


In [11]:
c.transpose() # Returns a view of the array with axes transposed.

array([[[ 1],
        [ 6],
        [11]],

       [[ 2],
        [ 7],
        [12]],

       [[ 3],
        [ 8],
        [13]],

       [[ 4],
        [ 9],
        [14]],

       [[ 5],
        [10],
        [15]]])

In [12]:
c

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [13]:
c.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
c.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [15]:
for a in c:
    for b in a:
        print(b)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [16]:
for arr in np.nditer(c):
    print(arr, end=',')

1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,

In [17]:
np.where(c//3==0)

(array([0, 0], dtype=int64),
 array([0, 0], dtype=int64),
 array([0, 1], dtype=int64))

In [18]:
c

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [19]:
np.array_split(c, 5)

[array([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15]]]),
 array([], shape=(0, 3, 5), dtype=int32),
 array([], shape=(0, 3, 5), dtype=int32),
 array([], shape=(0, 3, 5), dtype=int32),
 array([], shape=(0, 3, 5), dtype=int32)]

In [20]:
np.split(c, indices_or_sections=[3,4,5,0])

[array([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15]]]),
 array([], shape=(0, 3, 5), dtype=int32),
 array([], shape=(0, 3, 5), dtype=int32),
 array([], shape=(0, 3, 5), dtype=int32),
 array([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15]]])]

# Array Slicing

In [21]:
arr = np.array([i for i in range(1,6)])
arr

array([1, 2, 3, 4, 5])

In [22]:
arr[0:10] # arr[start: end-1: step]

array([1, 2, 3, 4, 5])

In [23]:
arr[-3:-1]

array([3, 4])

In [24]:
arr[-3:0]

array([], dtype=int32)

In [25]:
arr[-3:]

array([3, 4, 5])

In [26]:
arr[::2] # step 2

array([1, 3, 5])

In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

print(arr.base)
print(x.base)

[42  2  3  4  5]
[42  2  3  4  5]
None
[42  2  3  4  5]


In [28]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x, end = ' ')

1 2 3 4 5 6 7 8 

# Numpy Functions

In [29]:
# Return a new array of given shape and type, without initializing entries.
np.empty((4,4), dtype=int) #here (4,4): defines the shape means 4X4 matrix.

array([[   0,    0,    0,    0],
       [   0,    0,    0,    0],
       [   0,    0, 1344,    0],
       [   0,  457,    0,  457]])

In [30]:
np.ones(6, dtype=int) 

array([1, 1, 1, 1, 1, 1])

In [31]:
np.ones(6, dtype=float) 

array([1., 1., 1., 1., 1., 1.])

In [32]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [33]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.ones((3,5), dtype=str)

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [35]:
np.zeros(4)

array([0., 0., 0., 0.])

In [36]:
np.zeros(4, dtype=int)

array([0, 0, 0, 0])

In [37]:
np.zeros((4,), dtype=float)

array([0., 0., 0., 0.])

In [38]:
np.zeros((3,3), dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.zeros((4,4), dtype=str)

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [40]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a = np.arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [42]:
c

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [43]:
c.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [44]:
c.flatten() #Return a copy of the array collapsed into one dimension.
# since, it is a copy change in child will not impact the original
# flatten method of ndarray object.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [45]:
c.ravel() # Return a flattened array.(passes references, change in child will impact parent too)
# ravel is faster compared with flatten() as it doesn't occupy any memory
# ravel is library level function.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])